In [1]:
#autoreload modules after changes
%load_ext autoreload
%autoreload 2

import sys
import os
sys.path.insert(1, os.getcwd()+ '/../')

In [2]:
from module.Preprocessor import Preprocessor

preprocessor = Preprocessor()

preprocessor.fit_train(train_filename="../data/train.tsv")

In [3]:
import pandas as pd
import numpy as np

train = pd.read_csv("../data/train.tsv", sep="\t")
train.head(2)

id_job                                           features
0  1864791934054678713  2,9835,9999,9941,9945,9386,9899,9421,9954,9952...
1 -7413918695841089440  2,9082,9999,9700,9669,9981,9729,9822,9667,9526...

In [4]:
features = pd.DataFrame(list(train.features.apply(preprocessor._get_float_feature_values)))
features.head(2)

0       1       2       3       4       5       6       7       8    \
0  2.0  9835.0  9999.0  9941.0  9945.0  9386.0  9899.0  9421.0  9954.0   
1  2.0  9082.0  9999.0  9700.0  9669.0  9981.0  9729.0  9822.0  9667.0   

      9    ...     247     248     249     250     251     252     253  \
0  9952.0  ...  8818.0  9954.0  9925.0  9934.0  8689.0  9958.0  9086.0   
1  9526.0  ...  9979.0  9752.0  9695.0  9676.0  9974.0  9788.0  9955.0   

      254     255     256  
0  9114.0  9950.0  9875.0  
1  9907.0  9747.0  9824.0  

[2 rows x 257 columns]

In [5]:
features = features.drop(columns=[0])

### Mean

In [6]:
mean_by_pandas = features.mean(axis=0).values
mean_by_pandas[:4]

array([9528.70212766, 9867.72090113, 9746.36795995, 9687.6795995 ])

In [7]:
mean_by_module = preprocessor._stats_features["2"]["mean"]
mean_by_module[:4]

array([9528.70212766, 9867.72090113, 9746.36795995, 9687.6795995 ])

In [8]:
np.linalg.norm(mean_by_pandas - mean_by_module)

0.0

### Std

In [9]:
std_by_pandas = features.std(axis=0).values
std_by_pandas[:4]

array([553.30249005, 560.63865162, 316.17831455, 412.5531271 ])

In [10]:
std_by_module = preprocessor._stats_features["2"]["std"]
std_by_module[:4]

array([552.95613478, 560.28770408, 315.98039383, 412.29487785])

In [11]:
np.linalg.norm(std_by_pandas - std_by_module)

4.011083135939738